version: '3'

services:
  node:
    build: .
    command: sleep 365d
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - stream-network
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - stream-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=stream_auth_user
      - MONGO_INITDB_ROOT_PASSWORD=stream_auth_password
      - MONGO_INITDB_DATABASE=stream_auth_db
networks:
  stream-network:
    driver: bridge