version: '3'

services:
  node:
    build: .
    command: sleep 365d
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db